### ISSUE TITLE
Path issue of gf command

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/blackcart#25]
In Blackcart, `which gf` command returns the path of gf command. However, in Blackdagger, `which gf` command doesn't work. 

The important aspect of this is that gf command is not found in Blackdagger and causes errors in YAML executions. 

The workaround for this is adding:
```
env:
  - HOME: /root/
  - LOG_DIR: ${HOME}/logs
  - PATH: /usr/local/bin:${PATH}
```
in YAML.

This issue may appear for other tools too. The environment addition solves it but we should delve into this and other path and environment discrepancy.
